version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mymongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  backend:
    image: cicdtest_backend
    # build: .
    ports:
      - 8080:8080
    container_name: backend